#!/usr/bin/python3
import sys
import getpass
import subprocess
import yaml
import os
import time

args = sys.argv
workdir = None
confdir = None
ymlconf = open(confdir + '/config.yaml')
config = yaml.load(ymlconf.read(), Loader=yaml.FullLoader)
servers = config["servers"]
keys = list(servers.keys())
ranges = list(range(1,len(servers.keys())+1))
try:
    if args[1] == "down":
        argument = args[2]
    else:
        argument = args[1]
except:
    pass
try:
    position = int(argument)
except:
    position = 0

for i in ranges:
    print('Enter ' + str(i) + ' for ' + keys[i-1] )
try:
    if argument in keys:
        print('Selected vpn ' + str(keys.index(argument)+1) + ': ' + argument)
        selectedvpn = argument
    elif position in ranges:
        print('Selected vpn ' + argument + ': ' + keys[int(argument)-1])
        selectedvpn = keys[int(argument)-1]
    else:
        choice = int(input("Enter your choice:"))
        selectedvpn = keys[choice -1]
except Exception as e:
    #print(e)
    choice = int(input("Enter your choice:"))
    selectedvpn = keys[choice -1]


if len(args) > 1:
    if args[1] == "down":
        compose = "docker-compose -f {}/vpn.{}.yml -p vpn.{} down".format(confdir,selectedvpn,selectedvpn)
        start = subprocess.Popen(compose,shell=True)
        try:
            os.remove("config/config.{}".format(selectedvpn))
        except:
            pass
        try:
            os.remove("config/pass.{}.txt".format(selectedvpn))
        except:
            pass
        try:
                for command in servers[selectedvpn]["hostondown"].keys():
                            run = subprocess.Popen(servers[selectedvpn]["hostondown"][command],shell=True)
        except:
                print("No ondown commands")

        exit()

newfile = "#!/usr/bin/env bash \n"
newfile = newfile + "server='" + servers[selectedvpn]["host"] + "'\n"
newfile = newfile + "options='" + servers[selectedvpn]["options"] + "'\n"
newfile = newfile + "user='" + servers[selectedvpn]["user"] + "'\n"
newfile = newfile + "ssh=" + str(servers[selectedvpn]["sshport"]) + "\n"
newfile = newfile + "proxy=" + str(servers[selectedvpn]["proxyport"]) + "\n"
newfile = newfile + "dns=" + str(servers[selectedvpn]["dnsport"]) + "\n"
newfile = newfile + "nat=" + str(servers[selectedvpn]["nat"]).lower()
configfile = "{}/config/config.{}".format(workdir,selectedvpn)
passfile = "{}/config/pass.{}.txt".format(workdir,selectedvpn)
try:
    f = open(configfile,"x")
except:
    f = open(configfile,"w")
f.write(newfile)
f.close()
passwd = ""
for i in range(0,servers[selectedvpn]["pass"]):
    passwd = passwd + getpass.getpass(prompt='Password' + str(i + 1) + ': ', stream=None) + "\n"
try:
    p = open(passfile,"x")
except:
    p = open(passfile,"w")
p.write(passwd)
p.close()

compose = "docker-compose -f {}/vpn.{}.yml -p vpn.{} up".format(confdir,selectedvpn,selectedvpn)
start = subprocess.Popen(compose,shell=True)

check_status = "docker inspect -f='{{.State.Running}}' vpn.{}".format(selectedvpn)
while True:
    time.sleep(1)
    status = subprocess.run([check_status], capture_output=True, text=True, shell=True).stdout
    status = status.strip("\n")
    if status:
        break

try:
    for command in servers[selectedvpn]["hostonboot"].keys():
        run = subprocess.Popen(servers[selectedvpn]["hostonboot"][command],shell=True)
        print("Starting onboot commands")
except:
    print("No onboot commands")
