#!/usr/bin/python3
import sys
import getpass
import subprocess
import json
import os
args = sys.argv
workdir = os.path.dirname(os.path.realpath(__file__))
js = open(workdir + '/servers.json')
servers = json.loads(js.read())
keys = list(servers.keys())

for i in range(0,len(servers.keys())):
    num = i + 1
    print('Enter ' + str(num) + ' for ' + keys[i] )

choice = int(input("Enter your choice:"))
selectedvpn = keys[choice -1]

if len(args) > 1:
    if args[1] == "down":
        compose = "docker-compose -f {}/compose/vpn.{}.yml -p vpn.{} down".format(workdir,selectedvpn,selectedvpn)
        try:
            os.remove("config/config.{}".format(selectedvpn))
        except:
            pass
        try:
            os.remove("config/pass.{}.txt".format(selectedvpn))
        except:
            pass
        exit()

newfile = "#!/usr/bin/env bash \n"
newfile = newfile + "server='" + servers[selectedvpn]["host"] + "'\n"
newfile = newfile + "options='" + servers[selectedvpn]["options"] + "'\n"
newfile = newfile + "user='" + servers[selectedvpn]["user"] + "'"
configfile = "{}/config/config.{}".format(workdir,selectedvpn)
passfile = "{}/config/pass.{}.txt".format(workdir,selectedvpn)
try:
    f = open(configfile,"x")
except:
    f = open(configfile,"w")
f.write(newfile)
f.close()
passwd = ""
for i in range(0,servers[selectedvpn]["pass"]):
    passwd = passwd + getpass.getpass(prompt='Password' + str(i + 1) + ': ', stream=None) + "\n"
try:
    p = open(passfile,"x")
except:
    p = open(passfile,"w")
p.write(passwd)
p.close()

compose = "docker-compose -f {}/compose/vpn.{}.yml -p vpn.{} up".format(workdir,selectedvpn,selectedvpn)
start = subprocess.Popen(compose,shell=True)
